### ISSUE TITLE
bug: setMode is not a function in v4.33.1 (works in v4.32.0)

### ISSUE THREAD

**Issue by kozi** [stenciljs/core#6276]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/stenciljs/core/blob/main/CONTRIBUTING.md).
- [x] I agree to follow the [Code of Conduct](https://github.com/stenciljs/core/blob/main/CODE_OF_CONDUCT.md).
- [x] I have searched for [existing issues](https://github.com/stenciljs/core/issues) that already report this problem, without success.

### Stencil Version

4.33.1

### Current Behavior

The code described here <https://stenciljs.com/docs/styling#style-modes> does not work in `v4.33.1` in `v4.32.0` everything is fine.
```typescript
import { setMode } from '@stencil/core';

const defaultMode = 'md'; // Default to Material Design
setMode((el) => el.getAttribute('mode') || defaultMode);
```

![Image](https://github.com/user-attachments/assets/17c16f40-b487-4777-ad31-a87c45193502)

### Expected Behavior

The code should work like in `v4.32.0`.

### System Info

```shell
System: node 22.16.0
    Platform: windows (10.0.2***)
   CPU Model: AMD Ryzen 7 PRO ***
    Compiler: C:\...\node_modules\@stencil\core\compiler\stencil.js
       Build: 174898***
     Stencil: 4.33.1
  TypeScript: 5.5.4
      Rollup: 4.34.9
      Parse5: 7.2.1
      jQuery: 4.0.0-pre
      Terser: 5.37.0
```

### Steps to Reproduce

Just use the code snippet from above.

### Code Reproduction URL

https://github.com/stenciljs/

### Additional Information

Reprodution URL should not be mandatory.

**Comment by christian-bromann** [comment]
@kozi do you have a minimal reproduction case for this?

**Comment by kozi** [comment]
@christian-bromann https://github.com/kozi/stencil-set-mode-bug

![Image](https://github.com/user-attachments/assets/3f988080-0d53-4730-abfb-7142eb310a6a)

**Comment by kozi** [comment]
Changing the code of `global.ts` fixes the issue.
It is still a bit problematic because the previous code worked without any problems up to 4.32.x.

```typescript
import { setMode } from "@stencil/core";

export default async function() {
  console.log("typeof setMode:", typeof setMode);
}
```

**Comment by deleonio** [comment]
Hi @christian-bromann,

we need the `setMode` to trigger the theming. This is really important for us.

See here: https://github.com/public-ui/kolibri/blob/e86ef484cea9214c8d191d9e911f312f87f850ce/packages/components/src/global/script.ts#L6

**Comment by kozi** [comment]
> Hi [@christian-bromann](https://github.com/christian-bromann),
> 
> we need the `setMode` to trigger the theming. This is really important for us.
> 
> See here: https://github.com/public-ui/kolibri/blob/e86ef484cea9214c8d191d9e911f312f87f850ce/packages/components/src/global/script.ts#L6

The `setMode` method is available if you export a function (as default) as described in the documentation.

https://stenciljs.com/docs/config#globalscript

**Comment by christian-bromann** [comment]
@kozi we have two options here:

1. make it more clear in the docs that code should run in the exported function only so that imports are resolved properly
2. change the location where import scripts are being injected e.g. at the moment it is at the top of the runtime script. We could move it to the bottom but I am not fully sure if this has other implications.

Thoughts?

**Comment by kozi** [comment]
I am not familiar with the internal restrictions of the stencil framework. If certain functions can only be used in the ‘global’ callback function, they should simply be passed as a reference to the function.

```typescript
export default async function({ setMode }) {
  console.log("typeof setMode:", typeof setMode);
}
```

**Comment by christian-bromann** [comment]
@kozi I think this is definitely an option and something we should consider doing in a major version change. For now I will update the docs to make this behavior more clear.

**Comment by kozi** [comment]
@christian-bromann This does not have to be a breaking change. Until now, the function has not been passed an option object.
