### ISSUE TITLE
bug: Build failure starting from Stencil v4.28.0

### ISSUE THREAD

**Issue by hyyan** [stenciljs/core#6220]
We’ve encountered a build failure after upgrading from Stencil `v4.27.2` to `v4.28.0`. Everything was working fine with 4.27.2, but the build started consistently failing with 4.28.x. From the changelog, this appears related to the commit titled:

[`compiler: build: update rollup to latest`](https://github.com/stenciljs/core/commit/d54c44c55fc14a109ab3532e392962204d52d32c)

We haven’t found any upgrade guide or migration notes that mention changes which could explain this issue. We’ve tried to isolate the cause, but with 70+ components in the project, it’s difficult to pinpoint what exactly is triggering this.

We also attempted to reproduce the problem in a fresh Stencil starter app, but couldn't. So this seems to be something more complex.

Here’s the error we’re getting:

```
[16:06.8]  generate outputs finished in 3.12 s  MEM: 1037.0MB
[16:06.8]  aborted build, 6443ms  MEM: 1037.0MB

[ ERROR ]  Rollup: Plugin Error
           TypeError: context.warn is not a function at warn
           (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:240845:39) at
           resolveImportSpecifiers
           (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:240682:7) at async
           resolveLikeNode (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:240850:37)
           at async Object.handler
           (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:240956:26) at async
           nodeResolvePlugin.resolveId.handler
           (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:252124:22) at async
           _PluginDriver.hookFirstAndGetPlugin
           (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:231936:27) at async
           resolveId (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:216841:24) at
           async ModuleLoader.resolveId
           (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:231234:235) at async
           Object.resolveId (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:238643:24)
           at async _PluginDriver.hookFirstAndGetPlugin
           (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:231936:27) (plugin:
           commonjs--resolver, resolveId)
```

This occurs at the end of the build, right after output generation seems to finish. 

1. Was there a breaking change in plugin handling with the Rollup update?
2. Are there any recommendations for debugging this type of error across many components?
3. Is there any known pattern or usage that might trigger this (e.g., CommonJS modules, dynamic imports, etc.)?

Any help or pointers would be appreciated. If this rings a bell or there's a known workaround/fix in progress, we’d love to hear it.

```
      System: node 18.20.5
    Platform: darwin (24.2.0)
   CPU Model: Apple M2 Pro (10 cpus)
    Compiler: /Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js
       Build: 1741890846
     Stencil: 4.28.2 🎤
  TypeScript: 5.5.4
      Rollup: 4.34.9
      Parse5: 7.2.1
      jQuery: 4.0.0-pre
      Terser: 5.37.0
```

**Comment by johnjenkins** [comment]
hey @hyyan - the rollup that Stencil uses under-the-hood was updated from very old (~2) to current (~4). 
Whilst there shouldn't be any requirement for users to change anything, obviously if they use any rollup plugins or custom hooks perhaps something can break.
Could you run the build task with the `--debug` flag? Perhaps that will shed some light 🤞

**Comment by hyyan** [comment]
@johnjenkins Thanks for the quick reply.

I ran the build with the `--debug` flag, but unfortunately it doesn’t show anything more than what I already pasted—no additional context around the context.warn is not a function error.

We don’t use any Rollup plugins or custom hooks either, just the official @stencil/sass plugin.

Anything else we could try to help narrow it down?

**Comment by johnjenkins** [comment]
> Anything else we could try to help narrow it down?

hm not sure, sorry.

From this though, I can see that Stencil is breaking the rollup error handling chain (Rollup is attempting to 'warn' but there's no warn method so the build breaks) - so we can fix that at least, then you'll be able to see what the issue is with your build at least 😄

**Comment by hyyan** [comment]
Do you have any idea when a fix might be ready for this? Let me know if there’s anything we can do to help.

**Comment by christian-bromann** [comment]
Any contributions would be much appreciated. The core team has their own priorities and likely won't be able to work on every project issue. We depend on contributions from the community. Let me know if the team can help navigating the Stencil codebase.

**Comment by christian-bromann** [comment]
Sure, without looking into the problem, I can definitely say this problem is related to the Stencil compiler in `/src/compiler`, the error message indicates the line of code that causes the problem:

```sh
TypeError: context.warn is not a function at warn
           (/Users/Shared/Laptop/Github/dwc/node_modules/@stencil/core/compiler/stencil.js:240845
```
Take a look into the stencil package in your node_modules and find the original source within this repository. Then find a solution to the problem and propose a fix in the original source code. Lastly, writing tests to ensure we don't regress here frames the PR.

**Comment by hyyan** [comment]
Closing this because it relates to `@rollup/plugin-node-resolve`, not to Stencil core.  
For now, I modified `stencil.js` to expose the error and allow updating to the next version.  
Based on some unverified research, it seems you can also fix this by setting  
`nodeResolve: { browser: true, preferBuiltins: true }` in `stencil.config.ts`.

https://github.com/rollup/rollup-plugin-node-resolve/issues/196

**Comment by mikaelkaron** [comment]
I'm encountering the same problem when trying to use the [`qr`](https://www.npmjs.com/package/qr) package.

@hyyan what was the workaround you applied (besides downgrading to 4.27.2) if I may ask?

**Comment by mikaelkaron** [comment]
> @mikaelkaron, I didn’t downgrade. I modified the source in `stencil.js` directly to unmask the hidden error message. It turned out to be Rollup complaining about imports from another dependency. I’ve fixed it.
> 

Cool. Do you have a diff of the `stencil.js` you can share?

My understanding however is that the modification just changes the error message, so when you say "I've fixed it" I'm guessing you've fixed it in the dependency?

**Comment by hyyan** [comment]
@mikaelkaron I don’t have a patch to share, otherwise, I would’ve opened a PR. From what I understand, the issue is related to the Rollup resolve plugin. You can work around the masked error message by modifying `Stencil.js` file. In my case, the error pointed to `node_modules/@stencil/core/compiler/stencil.js:240845`. I changed `context.warn` to `console.warn`, ran it again, and that revealed the actual error.

When I said “I’ve fixed it,” I was referring to how I was using the dependency. The code was importing what are considered private classes, and Rollup didn’t like that.

**Comment by mikaelkaron** [comment]
> When I said “I’ve fixed it,” I was referring to how I was using the dependency. The code was importing what are considered private classes, and Rollup didn’t like that.

That really helped out - turned out I was trying to import from `qr/dom` instead of `qr/dom.js`. However it _would_ be helpful if this warning could be exposed so we could have avoided patching `stencil.js` manually.

Thank's again @hyyan for the help!

**Comment by johnjenkins** [comment]
@mikaelkaron perhaps you can make a pr to do that? 🙏

**Comment by crutkowski-84** [comment]
> Closing this because it relates to `@rollup/plugin-node-resolve`, not to Stencil core. For now, I modified `stencil.js` to expose the error and allow updating to the next version. Based on some unverified research, it seems you can unmask the error by setting `nodeResolve: { browser: true, preferBuiltins: true }` in `stencil.config.ts`.
> 
> [rollup/rollup-plugin-node-resolve#196](https://github.com/rollup/rollup-plugin-node-resolve/issues/196)

Updating my `stencil.config.ts` to include `nodeResolve: { browser: true, preferBuiltins: true }` did fix this error for me.
